/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.3
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OmniCore.Client.OpenAPIDateConverter;

namespace OmniCore.Model
{
    /// <summary>
    /// Details
    /// </summary>
    [DataContract(Name = "Details")]
    public partial class Details : IEquatable<Details>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Details" /> class.
        /// </summary>
        /// <param name="details">details.</param>
        public Details(string details = default(string))
        {
            this._Details = details;
        }

        /// <summary>
        /// Gets or Sets _Details
        /// </summary>
        [DataMember(Name = "details", EmitDefaultValue = false)]
        public string _Details { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Details {\n");
            sb.Append("  _Details: ").Append(_Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Details);
        }

        /// <summary>
        /// Returns true if Details instances are equal
        /// </summary>
        /// <param name="input">Instance of Details to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Details input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this._Details == input._Details ||
                    (this._Details != null &&
                    this._Details.Equals(input._Details))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Details != null)
                {
                    hashCode = (hashCode * 59) + this._Details.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
