/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.4
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OmniCore.Client.OpenAPIDateConverter;

namespace OmniCore.Model
{
    /// <summary>
    /// ListSinks
    /// </summary>
    [DataContract(Name = "ListSinks")]
    public partial class ListSinks : IEquatable<ListSinks>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListSinks" /> class.
        /// </summary>
        /// <param name="sinks">sinks.</param>
        public ListSinks(List<Sink> sinks = default(List<Sink>))
        {
            this.Sinks = sinks;
        }

        /// <summary>
        /// Gets or Sets Sinks
        /// </summary>
        [DataMember(Name = "sinks", EmitDefaultValue = false)]
        public List<Sink> Sinks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListSinks {\n");
            sb.Append("  Sinks: ").Append(Sinks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListSinks);
        }

        /// <summary>
        /// Returns true if ListSinks instances are equal
        /// </summary>
        /// <param name="input">Instance of ListSinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListSinks input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Sinks == input.Sinks ||
                    this.Sinks != null &&
                    input.Sinks != null &&
                    this.Sinks.SequenceEqual(input.Sinks)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Sinks != null)
                {
                    hashCode = (hashCode * 59) + this.Sinks.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
