/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OmniCore.Client.OpenAPIDateConverter;

namespace OmniCore.Model
{
    /// <summary>
    /// ListSinksSinksInnerConfig
    /// </summary>
    [DataContract(Name = "ListSinks_sinks_inner_config")]
    public partial class ListSinksSinksInnerConfig : IEquatable<ListSinksSinksInnerConfig>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListSinksSinksInnerConfig" /> class.
        /// </summary>
        /// <param name="connectionParameter">connectionParameter.</param>
        public ListSinksSinksInnerConfig(string connectionParameter = default(string))
        {
            this.ConnectionParameter = connectionParameter;
        }

        /// <summary>
        /// Gets or Sets ConnectionParameter
        /// </summary>
        [DataMember(Name = "connectionParameter", EmitDefaultValue = false)]
        public string ConnectionParameter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListSinksSinksInnerConfig {\n");
            sb.Append("  ConnectionParameter: ").Append(ConnectionParameter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListSinksSinksInnerConfig);
        }

        /// <summary>
        /// Returns true if ListSinksSinksInnerConfig instances are equal
        /// </summary>
        /// <param name="input">Instance of ListSinksSinksInnerConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListSinksSinksInnerConfig input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ConnectionParameter == input.ConnectionParameter ||
                    (this.ConnectionParameter != null &&
                    this.ConnectionParameter.Equals(input.ConnectionParameter))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ConnectionParameter != null)
                {
                    hashCode = (hashCode * 59) + this.ConnectionParameter.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
