/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OmniCore.Client.OpenAPIDateConverter;

namespace OmniCore.Model
{
    /// <summary>
    /// SetRetentionBody
    /// </summary>
    [DataContract(Name = "SetRetentionBody")]
    public partial class SetRetentionBody : IEquatable<SetRetentionBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetRetentionBody" /> class.
        /// </summary>
        /// <param name="retentionPeriod">retentionPeriod.</param>
        public SetRetentionBody(string retentionPeriod = default(string))
        {
            this.RetentionPeriod = retentionPeriod;
        }

        /// <summary>
        /// Gets or Sets RetentionPeriod
        /// </summary>
        [DataMember(Name = "retentionPeriod", EmitDefaultValue = false)]
        public string RetentionPeriod { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetRetentionBody {\n");
            sb.Append("  RetentionPeriod: ").Append(RetentionPeriod).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SetRetentionBody);
        }

        /// <summary>
        /// Returns true if SetRetentionBody instances are equal
        /// </summary>
        /// <param name="input">Instance of SetRetentionBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetRetentionBody input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RetentionPeriod == input.RetentionPeriod ||
                    (this.RetentionPeriod != null &&
                    this.RetentionPeriod.Equals(input.RetentionPeriod))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RetentionPeriod != null)
                {
                    hashCode = (hashCode * 59) + this.RetentionPeriod.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
