/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing BindRequestIdsGateway
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BindRequestIdsGatewayTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BindRequestIdsGateway
        //private BindRequestIdsGateway instance;

        public BindRequestIdsGatewayTests()
        {
            // TODO uncomment below to create an instance of BindRequestIdsGateway
            //instance = new BindRequestIdsGateway();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BindRequestIdsGateway
        /// </summary>
        [Fact]
        public void BindRequestIdsGatewayInstanceTest()
        {
            // TODO uncomment below to test "IsType" BindRequestIdsGateway
            //Assert.IsType<BindRequestIdsGateway>(instance);
        }


        /// <summary>
        /// Test the property 'DeviceIds'
        /// </summary>
        [Fact]
        public void DeviceIdsTest()
        {
            // TODO unit test for the property 'DeviceIds'
        }
        /// <summary>
        /// Test the property 'GatewayId'
        /// </summary>
        [Fact]
        public void GatewayIdTest()
        {
            // TODO unit test for the property 'GatewayId'
        }

    }

}
