/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.3
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing BindRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BindRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BindRequest
        //private BindRequest instance;

        public BindRequestTests()
        {
            // TODO uncomment below to create an instance of BindRequest
            //instance = new BindRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BindRequest
        /// </summary>
        [Fact]
        public void BindRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" BindRequest
            //Assert.IsType<BindRequest>(instance);
        }


        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'GatewayId'
        /// </summary>
        [Fact]
        public void GatewayIdTest()
        {
            // TODO unit test for the property 'GatewayId'
        }

    }

}
