/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing Config
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Config
        //private Config instance;

        public ConfigTests()
        {
            // TODO uncomment below to create an instance of Config
            //instance = new Config();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Config
        /// </summary>
        [Fact]
        public void ConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" Config
            //Assert.IsType<Config>(instance);
        }


        /// <summary>
        /// Test the property 'ConnectionParameter'
        /// </summary>
        [Fact]
        public void ConnectionParameterTest()
        {
            // TODO unit test for the property 'ConnectionParameter'
        }

    }

}
