/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing CreateVaultKeyBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateVaultKeyBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateVaultKeyBody
        //private CreateVaultKeyBody instance;

        public CreateVaultKeyBodyTests()
        {
            // TODO uncomment below to create an instance of CreateVaultKeyBody
            //instance = new CreateVaultKeyBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateVaultKeyBody
        /// </summary>
        [Fact]
        public void CreateVaultKeyBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateVaultKeyBody
            //Assert.IsType<CreateVaultKeyBody>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

    }

}
