/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing CustomOnboard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomOnboardTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomOnboard
        //private CustomOnboard instance;

        public CustomOnboardTests()
        {
            // TODO uncomment below to create an instance of CustomOnboard
            //instance = new CustomOnboard();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomOnboard
        /// </summary>
        [Fact]
        public void CustomOnboardInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomOnboard
            //Assert.IsType<CustomOnboard>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NumId'
        /// </summary>
        [Fact]
        public void NumIdTest()
        {
            // TODO unit test for the property 'NumId'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Fact]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }
        /// <summary>
        /// Test the property 'Registry'
        /// </summary>
        [Fact]
        public void RegistryTest()
        {
            // TODO unit test for the property 'Registry'
        }
        /// <summary>
        /// Test the property 'Blocked'
        /// </summary>
        [Fact]
        public void BlockedTest()
        {
            // TODO unit test for the property 'Blocked'
        }
        /// <summary>
        /// Test the property 'Capresent'
        /// </summary>
        [Fact]
        public void CapresentTest()
        {
            // TODO unit test for the property 'Capresent'
        }
        /// <summary>
        /// Test the property 'Subscription'
        /// </summary>
        [Fact]
        public void SubscriptionTest()
        {
            // TODO unit test for the property 'Subscription'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Fact]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }
        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Fact]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }
        /// <summary>
        /// Test the property 'Gateway'
        /// </summary>
        [Fact]
        public void GatewayTest()
        {
            // TODO unit test for the property 'Gateway'
        }
        /// <summary>
        /// Test the property 'GatewayConfig'
        /// </summary>
        [Fact]
        public void GatewayConfigTest()
        {
            // TODO unit test for the property 'GatewayConfig'
        }
        /// <summary>
        /// Test the property 'IsGateway'
        /// </summary>
        [Fact]
        public void IsGatewayTest()
        {
            // TODO unit test for the property 'IsGateway'
        }
        /// <summary>
        /// Test the property 'DeviceErrors'
        /// </summary>
        [Fact]
        public void DeviceErrorsTest()
        {
            // TODO unit test for the property 'DeviceErrors'
        }
        /// <summary>
        /// Test the property 'ClientOnline'
        /// </summary>
        [Fact]
        public void ClientOnlineTest()
        {
            // TODO unit test for the property 'ClientOnline'
        }
        /// <summary>
        /// Test the property 'LastConfigAckTime'
        /// </summary>
        [Fact]
        public void LastConfigAckTimeTest()
        {
            // TODO unit test for the property 'LastConfigAckTime'
        }
        /// <summary>
        /// Test the property 'LastConfigSendTime'
        /// </summary>
        [Fact]
        public void LastConfigSendTimeTest()
        {
            // TODO unit test for the property 'LastConfigSendTime'
        }
        /// <summary>
        /// Test the property 'LastErrorStatus'
        /// </summary>
        [Fact]
        public void LastErrorStatusTest()
        {
            // TODO unit test for the property 'LastErrorStatus'
        }
        /// <summary>
        /// Test the property 'LastErrorTime'
        /// </summary>
        [Fact]
        public void LastErrorTimeTest()
        {
            // TODO unit test for the property 'LastErrorTime'
        }
        /// <summary>
        /// Test the property 'LastEventTime'
        /// </summary>
        [Fact]
        public void LastEventTimeTest()
        {
            // TODO unit test for the property 'LastEventTime'
        }
        /// <summary>
        /// Test the property 'LastHeartbeatTime'
        /// </summary>
        [Fact]
        public void LastHeartbeatTimeTest()
        {
            // TODO unit test for the property 'LastHeartbeatTime'
        }
        /// <summary>
        /// Test the property 'LastStateTime'
        /// </summary>
        [Fact]
        public void LastStateTimeTest()
        {
            // TODO unit test for the property 'LastStateTime'
        }
        /// <summary>
        /// Test the property 'LogLevel'
        /// </summary>
        [Fact]
        public void LogLevelTest()
        {
            // TODO unit test for the property 'LogLevel'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Policy'
        /// </summary>
        [Fact]
        public void PolicyTest()
        {
            // TODO unit test for the property 'Policy'
        }
        /// <summary>
        /// Test the property 'CustomOnboardData'
        /// </summary>
        [Fact]
        public void CustomOnboardDataTest()
        {
            // TODO unit test for the property 'CustomOnboardData'
        }
        /// <summary>
        /// Test the property 'IsApprove'
        /// </summary>
        [Fact]
        public void IsApproveTest()
        {
            // TODO unit test for the property 'IsApprove'
        }

    }

}
