/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceConfig
        //private DeviceConfig instance;

        public DeviceConfigTests()
        {
            // TODO uncomment below to create an instance of DeviceConfig
            //instance = new DeviceConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceConfig
        /// </summary>
        [Fact]
        public void DeviceConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceConfig
            //Assert.IsType<DeviceConfig>(instance);
        }


        /// <summary>
        /// Test the property 'Acknowledged'
        /// </summary>
        [Fact]
        public void AcknowledgedTest()
        {
            // TODO unit test for the property 'Acknowledged'
        }
        /// <summary>
        /// Test the property 'BinaryData'
        /// </summary>
        [Fact]
        public void BinaryDataTest()
        {
            // TODO unit test for the property 'BinaryData'
        }
        /// <summary>
        /// Test the property 'CloudUpdateTime'
        /// </summary>
        [Fact]
        public void CloudUpdateTimeTest()
        {
            // TODO unit test for the property 'CloudUpdateTime'
        }
        /// <summary>
        /// Test the property 'DeviceAckTime'
        /// </summary>
        [Fact]
        public void DeviceAckTimeTest()
        {
            // TODO unit test for the property 'DeviceAckTime'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }

    }

}
