/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceConfiguration
        //private DeviceConfiguration instance;

        public DeviceConfigurationTests()
        {
            // TODO uncomment below to create an instance of DeviceConfiguration
            //instance = new DeviceConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceConfiguration
        /// </summary>
        [Fact]
        public void DeviceConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceConfiguration
            //Assert.IsType<DeviceConfiguration>(instance);
        }


        /// <summary>
        /// Test the property 'BinaryData'
        /// </summary>
        [Fact]
        public void BinaryDataTest()
        {
            // TODO unit test for the property 'BinaryData'
        }
        /// <summary>
        /// Test the property 'Subfolder'
        /// </summary>
        [Fact]
        public void SubfolderTest()
        {
            // TODO unit test for the property 'Subfolder'
        }
        /// <summary>
        /// Test the property 'VersionToUpdate'
        /// </summary>
        [Fact]
        public void VersionToUpdateTest()
        {
            // TODO unit test for the property 'VersionToUpdate'
        }

    }

}
