/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.10
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceOnline
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceOnlineTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceOnline
        //private DeviceOnline instance;

        public DeviceOnlineTests()
        {
            // TODO uncomment below to create an instance of DeviceOnline
            //instance = new DeviceOnline();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceOnline
        /// </summary>
        [Fact]
        public void DeviceOnlineInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceOnline
            //Assert.IsType<DeviceOnline>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Registry'
        /// </summary>
        [Fact]
        public void RegistryTest()
        {
            // TODO unit test for the property 'Registry'
        }
        /// <summary>
        /// Test the property 'ClientOnline'
        /// </summary>
        [Fact]
        public void ClientOnlineTest()
        {
            // TODO unit test for the property 'ClientOnline'
        }
        /// <summary>
        /// Test the property 'LastHeartbeatTime'
        /// </summary>
        [Fact]
        public void LastHeartbeatTimeTest()
        {
            // TODO unit test for the property 'LastHeartbeatTime'
        }
        /// <summary>
        /// Test the property 'Subscription'
        /// </summary>
        [Fact]
        public void SubscriptionTest()
        {
            // TODO unit test for the property 'Subscription'
        }

    }

}
