/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.10
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing EnableEncryptionBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnableEncryptionBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnableEncryptionBody
        //private EnableEncryptionBody instance;

        public EnableEncryptionBodyTests()
        {
            // TODO uncomment below to create an instance of EnableEncryptionBody
            //instance = new EnableEncryptionBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnableEncryptionBody
        /// </summary>
        [Fact]
        public void EnableEncryptionBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnableEncryptionBody
            //Assert.IsType<EnableEncryptionBody>(instance);
        }


        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'IsEncrypted'
        /// </summary>
        [Fact]
        public void IsEncryptedTest()
        {
            // TODO unit test for the property 'IsEncrypted'
        }
        /// <summary>
        /// Test the property 'EncryptionKeyId'
        /// </summary>
        [Fact]
        public void EncryptionKeyIdTest()
        {
            // TODO unit test for the property 'EncryptionKeyId'
        }

    }

}
