/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.5
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorFrame
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorFrameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorFrame
        //private ErrorFrame instance;

        public ErrorFrameTests()
        {
            // TODO uncomment below to create an instance of ErrorFrame
            //instance = new ErrorFrame();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorFrame
        /// </summary>
        [Fact]
        public void ErrorFrameInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorFrame
            //Assert.IsType<ErrorFrame>(instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
