/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing EventNotificationConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventNotificationConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventNotificationConfig
        //private EventNotificationConfig instance;

        public EventNotificationConfigTests()
        {
            // TODO uncomment below to create an instance of EventNotificationConfig
            //instance = new EventNotificationConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventNotificationConfig
        /// </summary>
        [Fact]
        public void EventNotificationConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventNotificationConfig
            //Assert.IsType<EventNotificationConfig>(instance);
        }


        /// <summary>
        /// Test the property 'PubsubTopicName'
        /// </summary>
        [Fact]
        public void PubsubTopicNameTest()
        {
            // TODO unit test for the property 'PubsubTopicName'
        }
        /// <summary>
        /// Test the property 'SubfolderMatches'
        /// </summary>
        [Fact]
        public void SubfolderMatchesTest()
        {
            // TODO unit test for the property 'SubfolderMatches'
        }

    }

}
