/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.5
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing ExportDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExportDetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExportDetail
        //private ExportDetail instance;

        public ExportDetailTests()
        {
            // TODO uncomment below to create an instance of ExportDetail
            //instance = new ExportDetail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExportDetail
        /// </summary>
        [Fact]
        public void ExportDetailInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExportDetail
            //Assert.IsType<ExportDetail>(instance);
        }


        /// <summary>
        /// Test the property 'Subscription'
        /// </summary>
        [Fact]
        public void SubscriptionTest()
        {
            // TODO unit test for the property 'Subscription'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Fact]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'Nooffiles'
        /// </summary>
        [Fact]
        public void NooffilesTest()
        {
            // TODO unit test for the property 'Nooffiles'
        }
        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [Fact]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }
        /// <summary>
        /// Test the property 'Done'
        /// </summary>
        [Fact]
        public void DoneTest()
        {
            // TODO unit test for the property 'Done'
        }

    }

}
