/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.10
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing GetReplaysResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetReplaysResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetReplaysResponse
        //private GetReplaysResponse instance;

        public GetReplaysResponseTests()
        {
            // TODO uncomment below to create an instance of GetReplaysResponse
            //instance = new GetReplaysResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetReplaysResponse
        /// </summary>
        [Fact]
        public void GetReplaysResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetReplaysResponse
            //Assert.IsType<GetReplaysResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }

    }

}
