/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing HttpConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HttpConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HttpConfig
        //private HttpConfig instance;

        public HttpConfigTests()
        {
            // TODO uncomment below to create an instance of HttpConfig
            //instance = new HttpConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HttpConfig
        /// </summary>
        [Fact]
        public void HttpConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" HttpConfig
            //Assert.IsType<HttpConfig>(instance);
        }


        /// <summary>
        /// Test the property 'HttpEnabledState'
        /// </summary>
        [Fact]
        public void HttpEnabledStateTest()
        {
            // TODO unit test for the property 'HttpEnabledState'
        }

    }

}
