/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.6
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing ListDeviceRegistries
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListDeviceRegistriesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListDeviceRegistries
        //private ListDeviceRegistries instance;

        public ListDeviceRegistriesTests()
        {
            // TODO uncomment below to create an instance of ListDeviceRegistries
            //instance = new ListDeviceRegistries();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListDeviceRegistries
        /// </summary>
        [Fact]
        public void ListDeviceRegistriesInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListDeviceRegistries
            //Assert.IsType<ListDeviceRegistries>(instance);
        }


        /// <summary>
        /// Test the property 'DeviceRegistries'
        /// </summary>
        [Fact]
        public void DeviceRegistriesTest()
        {
            // TODO unit test for the property 'DeviceRegistries'
        }
        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

    }

}
