/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.6
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing MetricsResponseDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetricsResponseDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MetricsResponseDetails
        //private MetricsResponseDetails instance;

        public MetricsResponseDetailsTests()
        {
            // TODO uncomment below to create an instance of MetricsResponseDetails
            //instance = new MetricsResponseDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetricsResponseDetails
        /// </summary>
        [Fact]
        public void MetricsResponseDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" MetricsResponseDetails
            //Assert.IsType<MetricsResponseDetails>(instance);
        }


        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }
        /// <summary>
        /// Test the property 'NoOfFiles'
        /// </summary>
        [Fact]
        public void NoOfFilesTest()
        {
            // TODO unit test for the property 'NoOfFiles'
        }
        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [Fact]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }
        /// <summary>
        /// Test the property 'Noofoperations'
        /// </summary>
        [Fact]
        public void NoofoperationsTest()
        {
            // TODO unit test for the property 'Noofoperations'
        }
        /// <summary>
        /// Test the property 'NoOfReplays'
        /// </summary>
        [Fact]
        public void NoOfReplaysTest()
        {
            // TODO unit test for the property 'NoOfReplays'
        }
        /// <summary>
        /// Test the property 'NoOfExports'
        /// </summary>
        [Fact]
        public void NoOfExportsTest()
        {
            // TODO unit test for the property 'NoOfExports'
        }
        /// <summary>
        /// Test the property 'Operations'
        /// </summary>
        [Fact]
        public void OperationsTest()
        {
            // TODO unit test for the property 'Operations'
        }
        /// <summary>
        /// Test the property 'DetailsForTimePeriod'
        /// </summary>
        [Fact]
        public void DetailsForTimePeriodTest()
        {
            // TODO unit test for the property 'DetailsForTimePeriod'
        }

    }

}
