/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.5
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing MetricsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetricsDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MetricsData
        //private MetricsData instance;

        public MetricsDataTests()
        {
            // TODO uncomment below to create an instance of MetricsData
            //instance = new MetricsData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MetricsData
        /// </summary>
        [Fact]
        public void MetricsDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" MetricsData
            //Assert.IsType<MetricsData>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'TotalExports'
        /// </summary>
        [Fact]
        public void TotalExportsTest()
        {
            // TODO unit test for the property 'TotalExports'
        }
        /// <summary>
        /// Test the property 'TotalReplays'
        /// </summary>
        [Fact]
        public void TotalReplaysTest()
        {
            // TODO unit test for the property 'TotalReplays'
        }

    }

}
