/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.6
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing MqttConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MqttConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MqttConfig
        //private MqttConfig instance;

        public MqttConfigTests()
        {
            // TODO uncomment below to create an instance of MqttConfig
            //instance = new MqttConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MqttConfig
        /// </summary>
        [Fact]
        public void MqttConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" MqttConfig
            //Assert.IsType<MqttConfig>(instance);
        }


        /// <summary>
        /// Test the property 'MqttEnabledState'
        /// </summary>
        [Fact]
        public void MqttEnabledStateTest()
        {
            // TODO unit test for the property 'MqttEnabledState'
        }

    }

}
