/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.6
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing OperationMetrics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OperationMetricsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OperationMetrics
        //private OperationMetrics instance;

        public OperationMetricsTests()
        {
            // TODO uncomment below to create an instance of OperationMetrics
            //instance = new OperationMetrics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OperationMetrics
        /// </summary>
        [Fact]
        public void OperationMetricsInstanceTest()
        {
            // TODO uncomment below to test "IsType" OperationMetrics
            //Assert.IsType<OperationMetrics>(instance);
        }


        /// <summary>
        /// Test the property 'NoOfFiles'
        /// </summary>
        [Fact]
        public void NoOfFilesTest()
        {
            // TODO unit test for the property 'NoOfFiles'
        }
        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [Fact]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }
        /// <summary>
        /// Test the property 'Operation'
        /// </summary>
        [Fact]
        public void OperationTest()
        {
            // TODO unit test for the property 'Operation'
        }
        /// <summary>
        /// Test the property 'Noofoperations'
        /// </summary>
        [Fact]
        public void NoofoperationsTest()
        {
            // TODO unit test for the property 'Noofoperations'
        }
        /// <summary>
        /// Test the property 'Updatedon'
        /// </summary>
        [Fact]
        public void UpdatedonTest()
        {
            // TODO unit test for the property 'Updatedon'
        }
        /// <summary>
        /// Test the property 'Registryid'
        /// </summary>
        [Fact]
        public void RegistryidTest()
        {
            // TODO unit test for the property 'Registryid'
        }

    }

}
