/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.2
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing PublicKeyCredential
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicKeyCredentialTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicKeyCredential
        //private PublicKeyCredential instance;

        public PublicKeyCredentialTests()
        {
            // TODO uncomment below to create an instance of PublicKeyCredential
            //instance = new PublicKeyCredential();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicKeyCredential
        /// </summary>
        [Fact]
        public void PublicKeyCredentialInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicKeyCredential
            //Assert.IsType<PublicKeyCredential>(instance);
        }


        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

    }

}
