/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing RegistryCertificate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegistryCertificateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegistryCertificate
        //private RegistryCertificate instance;

        public RegistryCertificateTests()
        {
            // TODO uncomment below to create an instance of RegistryCertificate
            //instance = new RegistryCertificate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegistryCertificate
        /// </summary>
        [Fact]
        public void RegistryCertificateInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegistryCertificate
            //Assert.IsType<RegistryCertificate>(instance);
        }


        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Fact]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }

    }

}
