/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing RegistryCredential
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegistryCredentialTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegistryCredential
        //private RegistryCredential instance;

        public RegistryCredentialTests()
        {
            // TODO uncomment below to create an instance of RegistryCredential
            //instance = new RegistryCredential();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegistryCredential
        /// </summary>
        [Fact]
        public void RegistryCredentialInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegistryCredential
            //Assert.IsType<RegistryCredential>(instance);
        }


        /// <summary>
        /// Test the property 'PublicKeyCertificate'
        /// </summary>
        [Fact]
        public void PublicKeyCertificateTest()
        {
            // TODO unit test for the property 'PublicKeyCertificate'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
