/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing SetRetentionBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetRetentionBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetRetentionBody
        //private SetRetentionBody instance;

        public SetRetentionBodyTests()
        {
            // TODO uncomment below to create an instance of SetRetentionBody
            //instance = new SetRetentionBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetRetentionBody
        /// </summary>
        [Fact]
        public void SetRetentionBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetRetentionBody
            //Assert.IsType<SetRetentionBody>(instance);
        }


        /// <summary>
        /// Test the property 'RetentionPeriod'
        /// </summary>
        [Fact]
        public void RetentionPeriodTest()
        {
            // TODO unit test for the property 'RetentionPeriod'
        }

    }

}
