/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.10
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing Sink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SinkTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Sink
        //private Sink instance;

        public SinkTests()
        {
            // TODO uncomment below to create an instance of Sink
            //instance = new Sink();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Sink
        /// </summary>
        [Fact]
        public void SinkInstanceTest()
        {
            // TODO uncomment below to test "IsType" Sink
            //Assert.IsType<Sink>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Subscription'
        /// </summary>
        [Fact]
        public void SubscriptionTest()
        {
            // TODO unit test for the property 'Subscription'
        }
        /// <summary>
        /// Test the property '_Sink'
        /// </summary>
        [Fact]
        public void _SinkTest()
        {
            // TODO unit test for the property '_Sink'
        }
        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Createdon'
        /// </summary>
        [Fact]
        public void CreatedonTest()
        {
            // TODO unit test for the property 'Createdon'
        }
        /// <summary>
        /// Test the property 'Updatedon'
        /// </summary>
        [Fact]
        public void UpdatedonTest()
        {
            // TODO unit test for the property 'Updatedon'
        }

    }

}
