/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateDevice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateDeviceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateDevice
        //private UpdateDevice instance;

        public UpdateDeviceTests()
        {
            // TODO uncomment below to create an instance of UpdateDevice
            //instance = new UpdateDevice();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateDevice
        /// </summary>
        [Fact]
        public void UpdateDeviceInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateDevice
            //Assert.IsType<UpdateDevice>(instance);
        }


        /// <summary>
        /// Test the property 'Blocked'
        /// </summary>
        [Fact]
        public void BlockedTest()
        {
            // TODO unit test for the property 'Blocked'
        }
        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Fact]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }
        /// <summary>
        /// Test the property 'LogLevel'
        /// </summary>
        [Fact]
        public void LogLevelTest()
        {
            // TODO unit test for the property 'LogLevel'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
