/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateRegistry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateRegistryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateRegistry
        //private UpdateRegistry instance;

        public UpdateRegistryTests()
        {
            // TODO uncomment below to create an instance of UpdateRegistry
            //instance = new UpdateRegistry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateRegistry
        /// </summary>
        [Fact]
        public void UpdateRegistryInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateRegistry
            //Assert.IsType<UpdateRegistry>(instance);
        }


        /// <summary>
        /// Test the property 'Credentials'
        /// </summary>
        [Fact]
        public void CredentialsTest()
        {
            // TODO unit test for the property 'Credentials'
        }
        /// <summary>
        /// Test the property 'HttpConfig'
        /// </summary>
        [Fact]
        public void HttpConfigTest()
        {
            // TODO unit test for the property 'HttpConfig'
        }
        /// <summary>
        /// Test the property 'MqttConfig'
        /// </summary>
        [Fact]
        public void MqttConfigTest()
        {
            // TODO unit test for the property 'MqttConfig'
        }
        /// <summary>
        /// Test the property 'LogLevel'
        /// </summary>
        [Fact]
        public void LogLevelTest()
        {
            // TODO unit test for the property 'LogLevel'
        }
        /// <summary>
        /// Test the property 'EventNotificationConfigs'
        /// </summary>
        [Fact]
        public void EventNotificationConfigsTest()
        {
            // TODO unit test for the property 'EventNotificationConfigs'
        }
        /// <summary>
        /// Test the property 'LogNotificationConfig'
        /// </summary>
        [Fact]
        public void LogNotificationConfigTest()
        {
            // TODO unit test for the property 'LogNotificationConfig'
        }
        /// <summary>
        /// Test the property 'StateNotificationConfig'
        /// </summary>
        [Fact]
        public void StateNotificationConfigTest()
        {
            // TODO unit test for the property 'StateNotificationConfig'
        }

    }

}
