/*
 * OmniCore Model and State Management API
 *
 * This is an OmniCore Model and State Management server.
 *
 * The version of the OpenAPI document: 1.8.4
 * Contact: omnicoresupport@korewireless.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OmniCore.Api;
using OmniCore.Model;
using OmniCore.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OmniCore.Test.Model
{
    /// <summary>
    ///  Class for testing VaultStatusDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VaultStatusDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VaultStatusDetails
        //private VaultStatusDetails instance;

        public VaultStatusDetailsTests()
        {
            // TODO uncomment below to create an instance of VaultStatusDetails
            //instance = new VaultStatusDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VaultStatusDetails
        /// </summary>
        [Fact]
        public void VaultStatusDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" VaultStatusDetails
            //Assert.IsType<VaultStatusDetails>(instance);
        }


        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }
        /// <summary>
        /// Test the property 'StorageType'
        /// </summary>
        [Fact]
        public void StorageTypeTest()
        {
            // TODO unit test for the property 'StorageType'
        }
        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Fact]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'IsCreated'
        /// </summary>
        [Fact]
        public void IsCreatedTest()
        {
            // TODO unit test for the property 'IsCreated'
        }
        /// <summary>
        /// Test the property 'Updatedon'
        /// </summary>
        [Fact]
        public void UpdatedonTest()
        {
            // TODO unit test for the property 'Updatedon'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'MqttId'
        /// </summary>
        [Fact]
        public void MqttIdTest()
        {
            // TODO unit test for the property 'MqttId'
        }

    }

}
